
server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/supermarket
    username: hyeonsu
    password: hyeonsu
    driver-class-name: com.mysql.cj.jdbc.Driver

